### ISSUE TITLE
Lines -> Auto Indent (editor:auto-indent) misinterprets end)

### ISSUE THREAD

**Issue by JamesJahraus** [lucasmazza/language-elixir#18]
When end) it is interpreted as the end of the function, and incorrectly formats the module.

Example from: https://howistart.org/posts/elixir/1

Lines -> Auto Indent (editor:auto-indent) 

defmodule Portal.Door do
...
-- def pop(door) do
---- Agent.get_and_update(door, fn
---- []    -> {:error, []}
---- [h|t] -> {{:ok, h}, t}
---- end)
end
end

The auto-indent interprets end) as end for def pop.

Expected the auto-indent interprets end) as end for Agent.get_and_update:

defmodule Portal.Door do
...
--def pop(door) do
---- Agent.get_and_update(door, fn
---- []    -> {:error, []}
---- [h|t] -> {{:ok, h}, t}
---- end)
--end
end

**Comment by keathley** [comment]
The issue that is the `[] -> {:error, []}` and `[h|t] -> {{:ok, h}, t}` aren't indented for that update code block. When you add the `end` it moves back a line. Since both of those function definitions are _inside_ of the agent function then conventionally they should be indented anyway.

I've created a fix for this in #32
